name: Build, Release, and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            static_linking: true
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
            static_linking: false
          - target: x86_64-apple-darwin
            archive: zip
            static_linking: true
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          STATIC_LINKING: ${{ matrix.static_linking }}

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: release # Ensure release is created first
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Publish to crates.io
      - name: Publish to Crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
